PATCH: Move extensibilityPluginApi.d.ts to upper folder so testcafe doesnt choke on it:)
There are a lot of typescript errors - what the typescript version of testcafe thinks ... but there are none actually and we also dont want to check our Neos.Ui codebase via the ts version of typescript (thats why we use d.ts in the first place)

Now when running the tests via `yarn testcafe chrome Tests/IntegrationTests/Fixtures` you would get that error though:

Error: TypeScript compilation failed.
Neos.Neos.Ui/packages/framework-observable-react/src/useLatestValueFrom.ts (10, 8): Module '"Neos.Neos.Ui/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag
Neos.Neos.Ui/packages/framework-observable/src/Observable.ts (28, 9): Type '(subscriber: Subscriber<V>) => Readonly<{ unsubscribe: void | (() => void); }>' is not assignable to type '(subscriber: Subscriber<V>) => Subscription'.
  Call signature return types 'Readonly<{ unsubscribe: void | (() => void); }>' and 'Subscription' are incompatible.
    The types of 'unsubscribe' are incompatible between these types.