BUGFIX: New `translate()` function return address if no fallback specified and dont crash
Due to the assumption `fallback` is specified and a string we run in `substitutePlaceholders:22` into:

> TypeError: undefined is not an object (evaluating 'e.indexOf') —

Now instead we return the given translation address (as in Flow and with the Ui legacy translation functionality) and additionally emit a console warning:

> The translation address "Neos.Neos.Ui:Main:notexisint" cannot be resolved and no fallback was specified.